job('First Maven Project'){
    description("First Maven job generated by DSL on ${new Date()}, project hosted on Github")
    scm{
        git("https://github.com/ashishbattise24/hello-world.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
       maven('clean package', 'pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
